project_id = "gozasfvvgshljziijuwr"

[functions.send-contact-email]
verify_jwt = false

[functions.get-bale-products]
verify_jwt = false

[functions.add-product-images]
verify_jwt = false

[functions.manage-categories]
verify_jwt = false

[functions.manage-products]
verify_jwt = false

[functions.manage-product-images]
verify_jwt = false

[functions.generate-product-images]
verify_jwt = false

[functions.generate-stock-item-images]
verify_jwt = false

[functions.generate-single-stock-image]
verify_jwt = false

[functions.send-verification-pin]
verify_jwt = false

[functions.verify-pin]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.get-bales]
verify_jwt = false

[functions.send-sales-notification]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.track-bale-metric]
verify_jwt = false

[functions.reset-bale-metrics]
verify_jwt = false

[functions.fix-order-payment]
verify_jwt = false

[functions.initialize-paystack-payment]
verify_jwt = false

[functions.verify-paystack-payment]
verify_jwt = false
